name: example
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  expandable_text:
    path: ../

flutter:
  uses-material-design: true
